<?php
// Creates the canonical Accounts schema on PostgreSQL for a clean restore.
require_once __DIR__ . '/Database.php';
require_once __DIR__ . '/SchemaCatalog.php';

$db = Database::getConnection();
if ($db->getAttribute(PDO::ATTR_DRIVER_NAME) !== 'pgsql') {
    throw new RuntimeException('create_postgres_tables.php requires a PostgreSQL DSN.');
}

function pgDefinition(string $definition): string {
    $definition = preg_replace('/\bINT AUTO_INCREMENT\b/i', 'INTEGER GENERATED BY DEFAULT AS IDENTITY', $definition);
    $definition = preg_replace('/\bBIGINT AUTO_INCREMENT\b/i', 'BIGINT GENERATED BY DEFAULT AS IDENTITY', $definition);
    $definition = preg_replace('/\bTINYINT(?:\(1\))?\b/i', 'SMALLINT', $definition);
    $definition = preg_replace('/\bLONGTEXT\b/i', 'TEXT', $definition);
    $definition = preg_replace('/ENUM\([^)]*\)/i', 'TEXT', $definition);
    return preg_replace('/\s+ON UPDATE CURRENT_TIMESTAMP/i', '', $definition);
}

function pgColumns(array $columns): string {
    return implode(', ', array_map(fn($column) => '"' . $column . '"', $columns));
}

$catalog = SchemaCatalog::tables();
$db->beginTransaction();
try {
    foreach ($catalog as $tableName => $table) {
        $parts = [];
        foreach ($table['columns'] as $columnName => $column) {
            $parts[] = '"' . $columnName . '" ' . pgDefinition($column['definition']);
        }
        $parts[] = 'PRIMARY KEY (' . pgColumns($table['primary']) . ')';
        foreach ($table['foreign_keys'] as $constraintName => $foreignKey) {
            $sql = 'CONSTRAINT "' . $constraintName . '" FOREIGN KEY (' . pgColumns($foreignKey['columns']) . ')'
                . ' REFERENCES "' . $foreignKey['referenced_table'] . '" (' . pgColumns($foreignKey['referenced_columns']) . ')';
            if ($foreignKey['delete_rule'] !== 'RESTRICT') $sql .= ' ON DELETE ' . $foreignKey['delete_rule'];
            $parts[] = $sql;
        }
        $db->exec('CREATE TABLE IF NOT EXISTS "' . $tableName . '" (' . implode(', ', $parts) . ')');
        foreach ($table['indexes'] as $indexName => $index) {
            $db->exec('CREATE ' . ($index['unique'] ? 'UNIQUE ' : '') . 'INDEX IF NOT EXISTS "' . $indexName . '" ON "' . $tableName . '" (' . pgColumns($index['columns']) . ')');
        }
    }
    $db->commit();
} catch (Throwable $e) {
    $db->rollBack();
    throw $e;
}
echo "PostgreSQL schema ready.\n";
