image: atlassian/default-image:2

pipelines:
  branches:
    master:
      - parallel:
          - step:
              name: 'Automated Deployment'
              script:
                - curl https://your.web.server.com/automated_deployment.php
