(function(root){'use strict';
const MONTHS=['January','February','March','April','May','June','July','August','September','October','November','December'];
const money=new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'});
function normaliseRows(rows){if(!Array.isArray(rows))return[];return rows.map(row=>{const date=String(row.date||'');const monthIndex=Number(date.slice(5,7))-1;return{...row,amount:Number.parseFloat(row.amount)||0,year:date.slice(0,4),month:MONTHS[monthIndex]||'Unknown',isTransfer:row.transfer_id!==null&&row.transfer_id!==undefined&&String(row.transfer_id)!==''};}).filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.date)&&!row.isTransfer);}
function summariseRows(rows){const incoming=rows.reduce((sum,row)=>sum+Math.max(0,row.amount),0);const outgoing=rows.reduce((sum,row)=>sum+Math.abs(Math.min(0,row.amount)),0);const dates=rows.map(row=>row.date).sort();return{incoming,outgoing,net:incoming-outgoing,count:rows.length,firstDate:dates[0]||'',lastDate:dates[dates.length-1]||''};}
function buildMatrix(rows,keyField){const hierarchy=new Map(),totals={},keys=new Set();const add=(target,key,amount)=>{target[key]=(target[key]||0)+amount;target.Total=(target.Total||0)+amount;};rows.forEach(row=>{const segment=row.segment_name||'Unsegmented',category=row.category_name||'Uncategorised',tag=row.tag_name||'Untagged',key=row[keyField];if(!key)return;keys.add(key);if(!hierarchy.has(segment))hierarchy.set(segment,{totals:{},categories:new Map()});const segmentNode=hierarchy.get(segment);if(!segmentNode.categories.has(category))segmentNode.categories.set(category,{totals:{},tags:new Map()});const categoryNode=segmentNode.categories.get(category);if(!categoryNode.tags.has(tag))categoryNode.tags.set(tag,{totals:{}});[totals,segmentNode.totals,categoryNode.totals,categoryNode.tags.get(tag).totals].forEach(target=>add(target,key,row.amount));});const ordered=Array.from(keys).sort((a,b)=>keyField==='month'?MONTHS.indexOf(a)-MONTHS.indexOf(b):Number(a)-Number(b));const makeRow=(item,nodeTotals,children,meta)=>{const result={item,...meta};ordered.forEach(key=>{result[key]=nodeTotals[key]||0;});result.Total=nodeTotals.Total||0;if(children.length)result._children=children;return result;};const tableRows=Array.from(hierarchy,([segment,sn])=>makeRow(segment,sn.totals,Array.from(sn.categories,([category,cn])=>makeRow(category,cn.totals,Array.from(cn.tags,([tag,tn])=>makeRow(tag,tn.totals,[],{segment,category,tag})),{segment,category})),{segment}));return{keys:ordered,totals,rows:tableRows};}
if(typeof module!=='undefined'&&module.exports)module.exports={normaliseRows,summariseRows,buildMatrix};if(!root||!root.document)return;
document.addEventListener('DOMContentLoaded',()=>{const el=id=>document.getElementById(id),yearSelect=el('year-select'),refreshButton=el('refresh'),exportButton=el('export'),retryButton=el('pivot-retry'),state=el('pivot-state'),matrixCard=el('matrix-card'),detailCard=el('detail-card');let matrixTable=null,detailTable=null,currentRows=[],currentKeyField='year',requestController=null;
const setText=(id,value)=>{el(id).textContent=value;};const currency=value=>money.format(Number(value)||0);
function setBusy(busy){refreshButton.disabled=busy;refreshButton.classList.toggle('is-loading',busy);yearSelect.disabled=busy;el('pivot-summary').setAttribute('aria-busy',String(busy));}
function showState(kind,title,message){state.hidden=false;state.className=`pivot-state is-${kind}`;setText('pivot-state-title',title);setText('pivot-state-message',message);retryButton.hidden=kind!=='error';}function hideState(){state.hidden=true;}
async function fetchJson(url,signal){const response=await fetch(url,{signal});let payload;try{payload=await response.json();}catch(_){throw new Error('The server returned an unreadable response.');}if(!response.ok||(payload&&payload.error))throw new Error((payload&&payload.error)||`Request failed (${response.status}).`);return payload;}
function updateScope(year){currentKeyField=year==='all'?'year':'month';setText('scope-description',year==='all'?'Showing all available years, arranged by year.':`Showing ${year}, arranged month by month.`);}
function renderSummary(rows){const summary=summariseRows(rows);setText('summary-out',currency(summary.outgoing));setText('summary-in',currency(summary.incoming));setText('summary-net',currency(summary.net));setText('summary-count',summary.count.toLocaleString('en-GB'));setText('summary-coverage',summary.count?`${summary.firstDate} to ${summary.lastDate}`:'in selected period');el('summary-net-card').classList.toggle('is-negative',summary.net<0);}
function moneyColumn(title,field,totals){return{title,field,hozAlign:'right',sorter:'number',minWidth:112,formatter:'money',formatterParams:{symbol:'£',precision:2},bottomCalc:()=>totals[field]||0,bottomCalcFormatter:'money',bottomCalcFormatterParams:{symbol:'£',precision:2},cssClass:'cursor-pointer',cellClick:openDetail};}
function renderMatrix(rows){const matrix=buildMatrix(rows,currentKeyField),columns=[{title:'Segment / category / tag',field:'item',frozen:true,minWidth:210},...matrix.keys.map(key=>moneyColumn(key,key,matrix.totals)),moneyColumn('Total','Total',matrix.totals)];if(matrixTable&&typeof matrixTable.destroy==='function')matrixTable.destroy();el('pivot-table').replaceChildren();matrixTable=root.tailwindTabulator('#pivot-table',{data:matrix.rows,columns,layout:'fitDataStretch',modernResponsive:false,modernFreezeFirst:true,modernMaxHeight:'65vh',pagination:false,dataTree:true,dataTreeStartExpanded:false});matrixCard.hidden=false;exportButton.disabled=false;}
function detailColumns(){return[{title:'Date',field:'date',minWidth:105},{title:'Description',field:'description',minWidth:220},{title:'Category',field:'category_name',minWidth:130},{title:'Amount',field:'amount',hozAlign:'right',sorter:'number',minWidth:110,formatter:'money',formatterParams:{symbol:'£',precision:2}}];}
function openDetail(event,cell){const field=cell.getField();if(field==='item')return;const row=cell.getRow().getData();const filtered=currentRows.filter(item=>(!row.segment||(item.segment_name||'Unsegmented')===row.segment)&&(!row.category||(item.category_name||'Uncategorised')===row.category)&&(!row.tag||(item.tag_name||'Untagged')===row.tag)&&(field==='Total'||item[currentKeyField]===field));setText('detail-title',`${row.item} · ${field}`);setText('detail-summary',`${filtered.length} transaction${filtered.length===1?'':'s'} · ${currency(filtered.reduce((sum,item)=>sum+item.amount,0))} net movement`);detailCard.hidden=false;if(detailTable&&typeof detailTable.destroy==='function')detailTable.destroy();el('detail-table').replaceChildren();detailTable=root.tailwindTabulator('#detail-table',{data:filtered,columns:detailColumns(),layout:'fitColumns',modernMaxHeight:'28rem',pagination:filtered.length>30,paginationSize:30});detailCard.scrollIntoView({behavior:'smooth',block:'start'});}
function renderEmpty(){matrixCard.hidden=true;detailCard.hidden=true;exportButton.disabled=true;showState('empty','No transactions in this period','Choose another period to build the analysis. Internal transfers are intentionally excluded.');}
async function loadData(announce){if(requestController)requestController.abort();requestController=new AbortController();const year=yearSelect.value;updateScope(year);setBusy(true);detailCard.hidden=true;showState('loading','Building your analysis…','Organising transactions into a useful financial matrix.');let url='../php_backend/public/export_data.php';if(year!=='all')url+=`?start=${year}-01-01&end=${year}-12-31`;try{const payload=await fetchJson(url,requestController.signal);currentRows=normaliseRows(payload);renderSummary(currentRows);if(!currentRows.length)renderEmpty();else{renderMatrix(currentRows);hideState();}if(announce&&root.showMessage)root.showMessage('Pivot analysis refreshed.');}catch(error){if(error.name==='AbortError')return;matrixCard.hidden=true;exportButton.disabled=true;showState('error','We could not build the analysis',error.message||'Please try again.');if(announce&&root.showMessage)root.showMessage(error.message||'Pivot analysis failed.','error');}finally{setBusy(false);}}
async function loadYears(){try{const months=await fetchJson('../php_backend/public/transaction_months.php');Array.from(new Set((Array.isArray(months)?months:[]).map(item=>String(item.year)).filter(year=>/^\d{4}$/.test(year)))).sort((a,b)=>Number(b)-Number(a)).forEach(year=>{const option=document.createElement('option');option.value=year;option.textContent=year;yearSelect.appendChild(option);});}catch(_){if(root.showMessage)root.showMessage('Available years could not be loaded; showing all recorded data.','warning');}loadData(false);}
refreshButton.addEventListener('click',()=>loadData(true));retryButton.addEventListener('click',()=>loadData(true));yearSelect.addEventListener('change',()=>loadData(false));exportButton.addEventListener('click',()=>{if(matrixTable)matrixTable.download('csv',`pivot-${yearSelect.value}.csv`);});el('detail-close').addEventListener('click',()=>{detailCard.hidden=true;});loadYears();});
})(typeof window!=='undefined'?window:null);
