(function(){
    const UI=window.ProjectUI; const host=document.getElementById('projects-board'); const errorEl=document.getElementById('project-error');
    const search=document.getElementById('project-search'); const funding=document.getElementById('funding-filter'); const sort=document.getElementById('project-sort'); const chips=Array.from(document.querySelectorAll('.project-chip'));
    let projects=[];

    function benefit(icon,label,value){const box=document.createElement('div');box.className='project-benefit';const i=document.createElement('i');i.className=`fas ${icon}`;i.setAttribute('aria-hidden','true');const strong=document.createElement('strong');strong.textContent=String(UI.number(value));const span=document.createElement('span');span.textContent=label;box.append(i,strong,span);return box;}
    function action(project,icon,label,modifier,handler){const button=UI.actionButton(icon,`${label} ${project.name}`,modifier);button.addEventListener('click',async()=>{button.disabled=true;try{await handler();}finally{button.disabled=false;}});return button;}
    function renderTile(project){
        const used=UI.used(project);const status=UI.status(project);const tile=document.createElement('article');tile.className=`project-tile project-tile--${status}`;
        const tier=UI.priorityTier(project);const body=document.createElement('div');body.className='project-tile__body';const header=document.createElement('div');header.className='project-tile__header';const titleWrap=document.createElement('div');titleWrap.className='project-tile__title';const title=document.createElement('h3');title.textContent=project.name||'Untitled project';const fundingLine=document.createElement('p');fundingLine.textContent=project.funding_source||'Funding not set';const priority=document.createElement('span');priority.className=`project-priority-badge project-priority-badge--${tier.key}`;priority.textContent=tier.label;titleWrap.append(title,fundingLine,priority);
        const actions=document.createElement('div');actions.className='project-actions';
        const edit=action(project,'fa-pen','Edit','',async()=>{window.location.href=`project_add.html?id=${encodeURIComponent(project.id)}`;});
        const archive=action(project,'fa-box-archive','Archive','archive',async()=>{try{await UI.request({method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id,archived:1})});await load();UI.announce('Project archived');}catch(error){UI.announce(error.message,'error');}});
        const remove=action(project,'fa-trash','Delete','delete',async()=>{if(!confirm(`Permanently delete ${project.name}? This cannot be undone.`))return;try{await UI.request({method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id})});await load();UI.announce('Project deleted');}catch(error){UI.announce(error.message,'error');}});actions.append(edit,archive,remove);header.append(titleWrap,actions);
        const description=document.createElement('p');description.className='project-tile__description';description.textContent=project.description||project.rationale||'No description has been added yet.';
        const costLine=document.createElement('div');costLine.className='project-cost-line';const cost=document.createElement('div');const costLabel=document.createElement('span');costLabel.textContent='Mid-cost plan';const costValue=document.createElement('strong');costValue.textContent=UI.money(project.cost_medium);cost.append(costLabel,costValue);const usedValue=document.createElement('strong');usedValue.textContent=`${used.toFixed(0)}% used`;costLine.append(cost,usedValue);
        const track=document.createElement('div');track.className='project-progress';track.setAttribute('aria-label',`${project.name}: ${used.toFixed(0)}% of mid-cost plan spent`);const fill=document.createElement('span');fill.style.width=`${Math.min(used,100)}%`;track.appendChild(fill);
        const note=document.createElement('div');note.className='project-progress-note';const spent=document.createElement('span');spent.textContent=`${UI.money(project.spent)} spent`;const remaining=document.createElement('strong');const left=UI.number(project.cost_medium)-UI.number(project.spent);remaining.textContent=left>=0?`${UI.money(left)} remaining`:`${UI.money(Math.abs(left))} over`;note.append(spent,remaining);
        const signals=UI.prioritySignals(project);const benefits=document.createElement('div');benefits.className='project-benefits';benefits.append(benefit('fa-triangle-exclamation','Consequence',signals.consequence),benefit('fa-clock','Urgency',signals.urgency),benefit('fa-screwdriver-wrench','Preserves',signals.preservation),benefit('fa-sterling-sign','Financial',signals.financial),benefit('fa-heart','Daily life',signals.daily));
        const footer=document.createElement('div');footer.className='project-tile__footer';const score=document.createElement('span');score.className='project-score';score.append(document.createTextNode('Priority '));const scoreValue=document.createElement('strong');scoreValue.textContent=`${UI.priorityScore(project)}/100`;score.appendChild(scoreValue);const source=document.createElement('span');source.className='project-funding';source.textContent=project.estimated_time?`${UI.number(project.estimated_time)} months`:'Time not set';footer.append(score,source);
        body.append(header,description,costLine,track,note,benefits,footer);tile.appendChild(body);return tile;
    }
    function render(){
        const term=search.value.trim().toLowerCase();const selectedFunding=funding.value;const active=chips.filter(chip=>chip.getAttribute('aria-pressed')==='true').map(chip=>chip.dataset.filter);
        let filtered=projects.filter(project=>{const haystack=[project.name,project.description,project.rationale].join(' ').toLowerCase();if(term&&!haystack.includes(term))return false;if(selectedFunding&&project.funding_source!==selectedFunding)return false;return active.every(filter=>filter==='do_next'?['critical','important'].includes(UI.priorityTier(project).key):UI.status(project)===filter);});
        filtered.sort((a,b)=>sort.value==='score_asc'?UI.priorityScore(a)-UI.priorityScore(b):sort.value==='spend_desc'?UI.number(b.spent)-UI.number(a.spent):sort.value==='cost_desc'?UI.number(b.cost_medium)-UI.number(a.cost_medium):UI.comparePriority(a,b));
        UI.text('board-visible-count',String(filtered.length));UI.clear(host);if(!filtered.length){host.appendChild(UI.emptyState('No projects match','Try clearing a filter or create a new project.','fa-filter-circle-xmark'));return;}filtered.forEach(project=>host.appendChild(renderTile(project)));
    }
    function populateFunding(){UI.clear(funding);const all=document.createElement('option');all.value='';all.textContent='All funding';funding.appendChild(all);[...new Set(projects.map(project=>project.funding_source).filter(Boolean))].sort().forEach(source=>{const option=document.createElement('option');option.value=source;option.textContent=source;funding.appendChild(option);});}
    async function load(){errorEl.hidden=true;try{projects=await UI.request();UI.renderHero(projects,{valueId:'board-hero-value',messageId:'board-hero-message',signalId:'board-hero-signal',signalLabelId:'board-hero-signal-label',countId:'board-active-count',plannedId:'board-planned-total',spentId:'board-spent-total',priorityId:'board-priority-count'});populateFunding();render();}catch(error){UI.clear(host);host.appendChild(UI.emptyState('Projects could not be loaded','Refresh the page to try again.','fa-triangle-exclamation'));errorEl.textContent='The project board could not be loaded.';errorEl.hidden=false;}}
    search.addEventListener('input',render);funding.addEventListener('change',render);sort.addEventListener('change',render);chips.forEach(chip=>chip.addEventListener('click',()=>{chip.setAttribute('aria-pressed',chip.getAttribute('aria-pressed')==='true'?'false':'true');render();}));load();
})();
