(function(){
    const UI=window.ProjectUI;const host=document.getElementById('archive-list');const search=document.getElementById('archive-search');const errorEl=document.getElementById('archive-error');let projects=[];
    function stat(label,value,href){const wrap=document.createElement('div');wrap.className='project-archive-stat';const span=document.createElement('span');span.textContent=label;const strong=document.createElement('strong');if(href){const link=document.createElement('a');link.className='transaction-drilldown-link';link.href=href;link.textContent=value;strong.appendChild(link);}else strong.textContent=value;wrap.append(span,strong);return wrap;}
    function row(project){const item=document.createElement('article');item.className='project-archive-row';const copy=document.createElement('div');const title=document.createElement('h3');title.textContent=project.name||'Untitled project';const description=document.createElement('p');description.textContent=project.description||project.rationale||'No description recorded.';const tier=UI.priorityTier(project);const badge=document.createElement('span');badge.className=`project-priority-badge project-priority-badge--${tier.key}`;badge.textContent=tier.label;copy.append(title,badge,description);
        const restore=UI.actionButton('fa-box-open',`Restore ${project.name}`);restore.className='project-button project-button--secondary';const icon=restore.querySelector('i');const label=document.createElement('span');label.textContent='Restore';restore.appendChild(label);restore.addEventListener('click',async()=>{restore.disabled=true;try{await UI.request({method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:project.id,archived:0})});await load();UI.announce('Project restored');}catch(error){UI.announce(error.message,'error');}finally{restore.disabled=false;}});
        const spentHref=project.group_id?TransactionDrilldown.url({direction:'spending',transfer_scope:'exclude',ignored_scope:'include',dimension:'group',dimension_id:project.group_id,label:`${project.name} historic spending`}):null;item.append(copy,stat('Mid cost',UI.money(project.cost_medium)),stat('Spent',UI.money(project.spent),spentHref),stat('Priority',`${UI.priorityScore(project)}/100`),restore);return item;}
    function render(){const term=search.value.trim().toLowerCase();const filtered=projects.filter(project=>!term||[project.name,project.description,project.rationale].join(' ').toLowerCase().includes(term));UI.text('archive-visible-count',String(filtered.length));UI.clear(host);if(!filtered.length){host.appendChild(UI.emptyState(projects.length?'No archived projects match':'The archive is clear',projects.length?'Try a broader search.':'Archived projects will remain safely available here.','fa-box-open'));return;}filtered.forEach(project=>host.appendChild(row(project)));}
    async function load(){errorEl.hidden=true;try{projects=await UI.request(undefined,true);UI.renderHero(projects,{archived:true,valueId:'archive-hero-value',messageId:'archive-hero-message',signalId:'archive-hero-signal',signalLabelId:'archive-hero-signal-label',countId:'archive-count',plannedId:'archive-planned',spentId:'archive-spent',priorityId:'archive-priority'});render();}catch(error){UI.clear(host);host.appendChild(UI.emptyState('Archive could not be loaded','Refresh the page to try again.','fa-triangle-exclamation'));errorEl.textContent='Archived projects could not be loaded.';errorEl.hidden=false;}}
    search.addEventListener('input',render);load();
})();
