(function(){
    const UI=window.ProjectUI;const form=document.getElementById('project-form');const save=document.getElementById('save-project');const errorEl=document.getElementById('form-error');const idField=document.getElementById('project_id');
    const fields=['name','funding_source','description','rationale','cost_low','cost_medium','cost_high','recurring_cost','estimated_time','expected_lifespan','benefit_financial','benefit_quality','benefit_risk','benefit_sustainability','weight_risk','dependencies','risks'];
    function value(name){return form.elements[name].value;}
    function updatePreview(){
        UI.text('preview-name',value('name').trim()||'Untitled project');UI.text('preview-description',value('description').trim()||value('rationale').trim()||'Describe the outcome to make the project easier to compare.');UI.text('preview-cost',UI.money(value('cost_medium')));UI.text('preview-low',`Low ${UI.money(value('cost_low'))}`);UI.text('preview-high',`High ${UI.money(value('cost_high'))}`);
        const project={benefit_risk:value('benefit_risk'),weight_risk:value('weight_risk'),benefit_sustainability:value('benefit_sustainability'),benefit_financial:value('benefit_financial'),benefit_quality:value('benefit_quality')};const signal=UI.prioritySignals(project);const tier=UI.priorityTier(project);UI.text('preview-consequence',`${signal.consequence} / 5`);UI.text('preview-urgency',`${signal.urgency} / 5`);UI.text('preview-preservation',`${signal.preservation} / 5`);UI.text('preview-financial',`${signal.financial} / 5`);UI.text('preview-daily',`${signal.daily} / 5`);UI.text('preview-score',String(UI.priorityScore(project)));const tierEl=document.getElementById('preview-tier');tierEl.textContent=tier.label;tierEl.className=`project-priority-badge project-priority-badge--${tier.key}`;
    }
    function projectData(){const data={};fields.forEach(field=>data[field]=value(field));return data;}
    function validateCosts(){const low=UI.number(value('cost_low'));const mid=UI.number(value('cost_medium'));const high=UI.number(value('cost_high'));if(low&&mid&&low>mid){UI.announce('The low estimate must not exceed the likely estimate.','error');form.elements.cost_low.focus();return false;}if(mid&&high&&mid>high){UI.announce('The likely estimate must not exceed the high estimate.','error');form.elements.cost_high.focus();return false;}return true;}
    async function loadProject(){const id=new URLSearchParams(location.search).get('id');if(!id){updatePreview();return;}save.disabled=true;try{const projects=await UI.request();const project=projects.find(item=>String(item.id)===id);if(!project)throw new Error('Project not found');idField.value=project.id;fields.forEach(field=>{if(project[field]!==null&&project[field]!==undefined)form.elements[field].value=project[field];});document.title='Edit Project';window.updatePageHeader(formMain,{title:'Edit project',subtitle:'Refine the cost, priority signals, and delivery assumptions behind this plan.'});UI.text('preview-eyebrow','Live project brief');save.querySelector('span').textContent='Update project';updatePreview();}catch(error){errorEl.textContent=error.message==='Project not found'?'This project could not be found. Return to the board and choose another project.':'This project could not be loaded. Please try again.';errorEl.hidden=false;save.disabled=true;return;}save.disabled=false;}
    form.addEventListener('input',updatePreview);form.addEventListener('submit',async event=>{event.preventDefault();if(!validateCosts())return;const existingId=idField.value;const data=projectData();if(existingId)data.id=existingId;save.disabled=true;const label=save.querySelector('span');const previous=label.textContent;label.textContent=existingId?'Updating…':'Saving…';try{const result=await UI.request({method:existingId?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!existingId&&result.id){idField.value=result.id;history.replaceState(null,'',`?id=${encodeURIComponent(result.id)}`);document.title='Edit Project';window.updatePageHeader(formMain,{title:'Edit project',subtitle:'Refine the cost, priority signals, and delivery assumptions behind this plan.'});UI.text('preview-eyebrow','Live project brief');}label.textContent='Update project';UI.announce(existingId?'Project updated':'Project created');}catch(error){label.textContent=previous;UI.announce(error.message||'Project could not be saved','error');}finally{save.disabled=false;}});
    loadProject();
})();
