name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger automated deployment
        run: curl https://newaccounts.smeird.com/automated_deployment.php
